if not host:isHost() then return end

-- Создание страниц колеса действий
mainPage = action_wheel:newPage()
settingsPage = action_wheel:newPage()
action_wheel:setPage(mainPage) -- Задание активной страницы

-- Кнопки основной страницы
goToSettings = mainPage:newAction()
    :title("Настройки")
    :item("minecraft:command_block")
    :hoverColor(255 / 255, 122 / 255, 146 / 255)
    :color(255 / 255, 168 / 255, 175 / 255)
    :onLeftClick(function()
        action_wheel:setPage(settingsPage)
        sounds:playSound("block.calcite.place", player:getPos())
    end)
actions = mainPage:newAction()
    :title(updateActionButtonTitle())
    :item("minecraft:light")
    :hoverColor(255 / 255, 122 / 255, 146 / 255)
    :color(255 / 255, 168 / 255, 175 / 255)
    :onLeftClick(function()
        actionButtonPlay()
        actions:title(updateActionButtonTitle())
        sounds:playSound("block.calcite.place", player:getPos())
    end)
    :onRightClick(function()
        actionButtonStop()
        actions:title(updateActionButtonTitle())
        sounds:playSound("block.calcite.place", player:getPos())
    end)
    :onScroll(function(dir)
        actionButtonSelect(dir)
        actions:title(updateActionButtonTitle())
        sounds:playSound("block.calcite.place", player:getPos())
    end)

-- Кнопки страницы настроек
goToMain = settingsPage:newAction()
    :title("Главная страница")
    :item("minecraft:spectral_arrow")
    :hoverColor(255 / 255, 122 / 255, 146 / 255)
    :color(255 / 255, 168 / 255, 175 / 255)
    :onLeftClick(function()
        action_wheel:setPage(mainPage)
        sounds:playSound("block.calcite.place", player:getPos())
    end)
slimArms = settingsPage:newAction()
    :title("Руки")
    :item("minecraft:player_head")
    :hoverColor(255 / 255, 122 / 255, 146 / 255)
    :color(255 / 255, 168 / 255, 175 / 255)
    :toggleColor(255 / 255, 168 / 255, 175 / 255)
    :toggled(config:load("isArmsSlim"))
    :onToggle(function()
        if slimArms:isToggled() then slimArms:title("Руки: Алекс") else slimArms:title("Руки: Стив") end
        sounds:playSound("block.calcite.place", player:getPos())
        config:save("isArmsSlim", slimArms:isToggled())
        pings.setArms(slimArms:isToggled())
    end)
mouthHeight = settingsPage:newAction()
    :title("Высота рта\n §7Прокручивание вниз: -0.25\n Прокручивание вверх: +0.25")
    :item("minecraft:pufferfish")
    :hoverColor(255 / 255, 122 / 255, 146 / 255)
    :color(255 / 255, 168 / 255, 175 / 255)
    :onScroll(function (dir)
        local mouthPos = models.model.root.Body.Head.Face.Mouth:getPos()[2]
        config:save("mouthHeight", mouthPos)
        if dir > 0 and mouthPos < 6.25 then pings.mouthHeight(mouthPos + 0.25) elseif dir < 0 and mouthPos > -1.25 then pings.mouthHeight(mouthPos - 0.25) end
    end)
